version: "3.9"
services:
  db:
    image: postgres:16
    container_name: taskflow-db
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
    ports:
      - "5432:5432"
    volumes:
      - taskflow_pgdata:/var/lib/postgresql/data

volumes:
  taskflow_pgdata:
